package ui

// Key names as produced by tea.KeyPressMsg.String().
const (
	keyQuit      = "q"
	keyCtrlC     = "ctrl+c"
	keyHelp      = "?"
	keyTab       = "tab"
	keyShiftTab  = "shift+tab"
	keyUp        = "up"
	keyDown      = "down"
	keyJ         = "j"
	keyK         = "k"
	keyH         = "h"
	keyL         = "l"
	keyLeft      = "left"
	keyRight     = "right"
	keyEnter     = "enter"
	keySpace     = "space"
	keyEsc       = "esc"
	keyRefresh   = "r"
	keyRefreshAl = "R"
	keyTop       = "g"
	keyBottom    = "G"
	keyHalfDown  = "d"
	keyHalfUp    = "u"
	keyTab1      = "1"
	keyTab2      = "2"
	keyTab3      = "3"
	keyTab4      = "4"
	keyStage     = "space"
	keyStageAll  = "a"
	keyUnstageAl = "A"
	keyDiscard   = "x"
	keyDiscardAl = "X"
	keyCommit    = "C"
	keyStash     = "t"
	keyStashU    = "T"
	keyWS        = "w"
	keyFilter    = "/"
	keyCollapse  = "z"
	keyPin       = "*"
	keyPalette   = ":"
	keyPalette2  = "ctrl+p"
)
